# Site settings
title: NYC_GIS
#email: sethc23@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  a small suite of tools for managing and analyzing GIS data with a focus on NYC data
baseurl: "/NYC_GIS" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sethc23

# Build settings
markdown: kramdown
